version: "3.8"

services:
  db:
    image: mysql:8
    container_name: proyecto-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: ventasdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: back-ventas

    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: ventasdb
      DB_USERNAME: root
      DB_PASSWORD: admin123

    ports:
      - "8081:8080"

    depends_on:
      db:
        condition: service_started

    restart: always

  backdespachos:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: back-despachos
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: ventasdb
      DB_USERNAME: root
      DB_PASSWORD: admin123
    ports:
      - "8082:8081"
    depends_on:
      db:
        condition: service_started

    restart: always

  frontend:
    build: ./front_despacho
    container_name: front-despacho
    ports:
      - "8080:80"
    depends_on:
      - backventas
      - backdespachos

volumes:
  dbdata: