apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
        - name: back-ventas
          image: 856519093406.dkr.ecr.us-east-1.amazonaws.com/back-ventas:eks-v1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: back-ventas
  namespace: devops
spec:
  type: ClusterIP
  selector:
    app: back-ventas
  ports:
    - port: 8081
      targetPort: 8080