apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      containers:
        - name: front-despacho
          image: 856519093406.dkr.ecr.us-east-1.amazonaws.com/front-despacho:eks-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-despacho
  namespace: devops
spec:
  type: LoadBalancer
  selector:
    app: front-despacho
  ports:
    - port: 80
      targetPort: 80