apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: devops
type: Opaque
stringData:
  DB_ENDPOINT: "TU_ENDPOINT_DB"
  DB_PORT: "3306"
  DB_NAME: "ventasdb"
  DB_USERNAME: "root"
  DB_PASSWORD: "admin123"