name: Deploy Backend (AWS SSM)

on:
  push:
    branches: ["deploy"]
  workflow_run:
    workflows: ["Build & Push Backend (Docker Hub)"]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  BACKEND_INSTANCE_ID: i-00bcace9e71e29335 # REEMPLAZA SI CAMBIA EL ID DE TU INSTANCIA EC2

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Comprobar el código/repositorio
        uses: actions/checkout@v4

      - name: Configurar AWS credentials (manual con session token)
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}
          EOF
          cat > ~/.aws/config << EOF
          [default]
          region=${AWS_REGION}
          output=json
          EOF

      - name: Deploy backend por SSM (Comandos Docker directos)
        run: |
          aws ssm send-command \
            --region "${AWS_REGION}" \
            --document-name "AWS-RunShellScript" \
            --instance-ids "${BACKEND_INSTANCE_ID}" \
            --parameters commands="[
              \"docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tutorial-ssm-backend:latest\",
              \"docker stop backend-app || true\",
              \"docker rm backend-app || true\",
              \"docker run -d -p 8080:8080 --name backend-app ${{ secrets.DOCKERHUB_USERNAME }}/tutorial-ssm-backend:latest\"
            ]"